/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounting-accounts': RouteRecordInfo<'accounting-accounts', '/accounting/accounts', Record<never, never>, Record<never, never>>,
    'accounting-accounts-id': RouteRecordInfo<'accounting-accounts-id', '/accounting/accounts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-customers-id': RouteRecordInfo<'accounting-customers-id', '/accounting/customers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-expenses': RouteRecordInfo<'accounting-expenses', '/accounting/expenses', Record<never, never>, Record<never, never>>,
    'accounting-groups': RouteRecordInfo<'accounting-groups', '/accounting/groups', Record<never, never>, Record<never, never>>,
    'accounting-groups-id': RouteRecordInfo<'accounting-groups-id', '/accounting/groups/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-personnel': RouteRecordInfo<'accounting-personnel', '/accounting/personnel', Record<never, never>, Record<never, never>>,
    'accounting-personnel-id': RouteRecordInfo<'accounting-personnel-id', '/accounting/personnel/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'basvuru': RouteRecordInfo<'basvuru', '/basvuru', Record<never, never>, Record<never, never>>,
    'customers': RouteRecordInfo<'customers', '/customers', Record<never, never>, Record<never, never>>,
    'customers-id-edit': RouteRecordInfo<'customers-id-edit', '/customers/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'customers-create': RouteRecordInfo<'customers-create', '/customers/create', Record<never, never>, Record<never, never>>,
    'groups': RouteRecordInfo<'groups', '/groups', Record<never, never>, Record<never, never>>,
    'inventory': RouteRecordInfo<'inventory', '/inventory', Record<never, never>, Record<never, never>>,
    'inventory-labels': RouteRecordInfo<'inventory-labels', '/inventory/labels', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'management-roles': RouteRecordInfo<'management-roles', '/management/roles', Record<never, never>, Record<never, never>>,
    'management-settings': RouteRecordInfo<'management-settings', '/management/settings', Record<never, never>, Record<never, never>>,
    'management-settings-expense-categories': RouteRecordInfo<'management-settings-expense-categories', '/management/settings/expense-categories', Record<never, never>, Record<never, never>>,
    'management-users': RouteRecordInfo<'management-users', '/management/users', Record<never, never>, Record<never, never>>,
    'personnel': RouteRecordInfo<'personnel', '/personnel', Record<never, never>, Record<never, never>>,
    'personnel-id': RouteRecordInfo<'personnel-id', '/personnel/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'personnel-id-edit': RouteRecordInfo<'personnel-id-edit', '/personnel/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'personnel-applications': RouteRecordInfo<'personnel-applications', '/personnel/applications', Record<never, never>, Record<never, never>>,
    'personnel-create': RouteRecordInfo<'personnel-create', '/personnel/create', Record<never, never>, Record<never, never>>,
    'projects': RouteRecordInfo<'projects', '/projects', Record<never, never>, Record<never, never>>,
    'projects-id': RouteRecordInfo<'projects-id', '/projects/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'projects-id-edit': RouteRecordInfo<'projects-id-edit', '/projects/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'projects-id-zones': RouteRecordInfo<'projects-id-zones', '/projects/:id/zones', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'projects-create': RouteRecordInfo<'projects-create', '/projects/create', Record<never, never>, Record<never, never>>,
    'saha': RouteRecordInfo<'saha', '/saha', Record<never, never>, Record<never, never>>,
    'saha-day-id': RouteRecordInfo<'saha-day-id', '/saha/:dayId', { dayId: ParamValue<true> }, { dayId: ParamValue<false> }>,
  }
}
